### ISSUE TITLE
The wordlist contains a non-alphabetical character in "BLING!"

### ISSUE THREAD

**Issue by BerylsSpare** [sidward35/marvle#1]
**Describe the bug**
The wordlist contains a non-alphabetical character in "BLING!". Users can not enter the exclamation point in the user interface.

**To Reproduce**
1. Search the repo for BLING!

**Expected behavior**
The user would only expect solutions that contain the letters A-Z.

**Screenshots**
No screenshots at this time.

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all
 
**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Additional context**
BLING! was the marvle word of the day today. :/

**Comment by sidward35** [comment]
Fixed! Thanks for reporting. :)
